
---

- name: Adding pwquality PAM module
  hosts: all
  become: yes  

  tasks:

    - name: Add PAM rule
      community.general.pamd:
        name: common-password
        type: password
        control: required
        module_path: pam_permit.so
        new_type: password
        new_control: required
        new_module_path: pam_pwquality.so
        module_arguments: 'usercheck=1 enforce_for_root '
        state: after

